### ISSUE TITLE
Function mcrypt_get_block_size() is deprecated

### ISSUE THREAD

**Issue by suraj-jadhav** [anandsiddharth/laravel-paytm-wallet#8]
![screenshot from 2017-09-04 16 30 14](https://user-images.githubusercontent.com/31619340/30023751-5f22cf5a-918e-11e7-9137-be475ac66c54.png)

![sinppet 1](https://user-images.githubusercontent.com/31619340/30023644-ece283f4-918d-11e7-8bfa-76212a4f72b0.png)

**Comment by anandsiddharth** [comment]
@suraj-jadhav 
The paytm sdk has an issue.
I am working on it probably release another update in next week.

Please join me on gitter chat for updates:
https://gitter.im/laravel-paytm-wallet/Lobby?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge

Thanks

**Comment by anandsiddharth** [comment]
**UPDATE**
 
Paytm has not yet officially add support for PHP 7.1 in its SDK.
Prefer downgrading your PHP version to 7.0 and use the latest version of this package.

I will let the issue remain open because it's not yet genuinely solved.

Thanks!

**Comment by rssawhney** [comment]
@anandsiddharth i got a file from paytm where they are using the openssl functions for php 7.1
I can share it with you

**Comment by anandsiddharth** [comment]
Thanx @rssawhney !
I will check on that!

**Comment by rssawhney** [comment]
here's the file sent to me by paytm [encdec_paytm.txt](https://github.com/anandsiddharth/laravel-paytm-wallet/files/1522493/encdec_paytm.txt)

**Comment by anandsiddharth** [comment]
This issue is now fixed and now available for update via composer.
Release tag: v1.0.5
Commit : https://github.com/anandsiddharth/laravel-paytm-wallet/commit/e1d200870dfa1729df792a427bf7af494c527f7d

https://github.com/anandsiddharth/laravel-paytm-wallet/releases/tag/v1.0.5

Thanx @rssawhney :hugs: !

BTW prefer creating a pull request next time :smiley: 

Closing the issue as its resolved.
